### ISSUE TITLE
Hi Guys, any chance of making this a REST service? I am looking for an API related to conferences. Any clues?

### ISSUE THREAD

**Issue by tarang9211** [tech-conferences/confs.tech#104]
I'm looking to develop an iOS app for tech conferences so I was searching for an API service that provides this. If this repo is not the right match, could you possibly point me in the right direction?

**Comment by nimzco** [comment]
Hi @tarang9211, the web app uses the github endpoint to fetch JSON files:
- https://raw.githubusercontent.com/tech-conferences/javascript-conferences/master/conferences/2018/javascript.json
- https://raw.githubusercontent.com/tech-conferences/confs.tech/master/conferences/2018/ux.json
etc.

You could use the same since it's open source and the endpoint is provided by github.

There is nothing to add a conference through an API since it's all through these github hosted JSON files. There is probably a way to use the Github API to create pull requests but I haven't planned to work on that so far.

Nice idea for the iOS app though, let us know when you have something! 👍
