### ISSUE TITLE
Merge confs.tech and javascript-conferences

### ISSUE THREAD

**Issue by joellord** [tech-conferences/confs.tech#138]
Hi,
   any plans to merge both conference lists?  It would certainly make my life as a contributor much easier...

Thanks

**Comment by nimzco** [comment]
Hi @joellord!
Our initial idea with @prigara was that the `javascript-conferences` repo had already traction and active contributors, that's why we kept it. Also it shows first when you type [JavaScript conferences](https://github.com/search?utf8=%E2%9C%93&q=javascript+conferences&type=) on Github and has a good SEO on google.

We could have a link on their that redirects to `confs.tech`, or wait for this repo to _overstar_ the other one.

In any case, I'm planning on adding a form on the website that would create PRs automatically. It should be up soon, I'll update this post when it is!

**Comment by joellord** [comment]
I still prefer to add them manually in GH when I do batches. :)

**Comment by nimzco** [comment]
Hi @joellord , we've merged the two lists to this new repo: https://github.com/tech-conferences/conference-data/

I hope this helps! 👍
