### ISSUE TITLE
Stick to selected country when switching category

### ISSUE THREAD

**Issue by darahak** [tech-conferences/confs.tech#40]
If I choose a country and click on a different language category, it resets my country selection.
I think it would be nice to persist it when we switch languages. What do you think?

I'll look into it when I have some time (just getting started with React).

**Comment by nimzco** [comment]
I think it's a good idea. We just have to make sure this country is available in the new list since I'm only showing countries where there is conferences.

Simple example: 
There is Argentina for JS: https://confs.tech/javascript/Argentina
Not for CSS: https://confs.tech/css/Argentina

In this case we would need to piggy back to `All countries`

But thanks for the suggestion, it's a good idea 👍

**Comment by nimzco** [comment]
Fixed! 👍
