### ISSUE TITLE
Internal server error when trying to add a scala conference

### ISSUE THREAD

**Issue by urmaul** [tech-conferences/confs.tech#429]
I'm trying to add a conference and it fails:

POST request to https://api-confs-tech.herokuapp.com/api/conferences
with parameters:

name | value
-- | --
cfpEndDate | null
cfpUrl |  
city | Kyiv
comment |  
country | Ukraine
endDate | 2019-03-30
name | ScalaUA
startDate | 2019-03-29
topic | scala
twitter | @ScalaUA_Conf
url | https://www.scalaua.com

Response is:
{"status":500,"error":"Internal Server Error"}

**Comment by nimzco** [comment]
Hey @urmaul, thanks for reporting this. As you mentioned, that's because `scala.json` does not exist and the backend doesn't create the file in that scenario...
I'll create the file by hand right now since I don't have the time to implement that change on the backend.

Thanks for reporting it in any case! 👍 
I've opened an issue on `api.confs.tech` to track that!
