### ISSUE TITLE
Add another filter-tag #opensource for Open Source conferences

### ISSUE THREAD

**Issue by mkurzman** [tech-conferences/confs.tech#624]
Motivation:
Identify events organized by Open Source communities or Open Source foundations by filtering for #opensource

Examples:
- [Open Community Experience](https://www.ocxconf.org/) Mainz, Germany・October 22-24 => organized by Eclipse Foundation
- [Open Source Summit Europe](https://events.linuxfoundation.org/open-source-summit-europe) Vienna, Austria & Online・September 16-18 => organized by Linux Foundation

**Comment by dellagustin-sap** [comment]
Hello @cgrail , would a contribution to add this category be wanted by the maintainers?
I'm a member of the SAP Open Source Program Office and I would be interested in having the option to filter for conferences about Open Source.
I did a brief investigation and found some places where changes would be needed (e.g., https://github.com/tech-conferences/confs.tech/blob/bae7ad07687572ebe7a55054376d3f715914d6d1/src/components/config/index.ts#L3), but there are some gaps I could not fill.
As far as I understood, the data from https://github.com/tech-conferences/conference-data is transferred at some point to Algolia and it is fetch from there by the confs.tech frontend, but I could not find the moving parts that do that, and see what I would need to do to enable a new category. Could you help me with that?

**Comment by dellagustin-sap** [comment]
I created a draft PR with the necessary changes I have identified so far: https://github.com/tech-conferences/confs.tech/pull/780

**Comment by cgrail** [comment]
Hi @dellagustin-sap 

thanks for reaching out. Currently it's not that simple. The topic of a conference is not simply a tag. Currently the topic of a conference is determined by the fact in which file the conference was added. For example the following conference is added to three topics by being added to three different files:
https://github.com/tech-conferences/conference-data/pull/7253/files

I have spent a whole lot of time to find possible duplicates and almost duplicate entries and to keep conferences with different topics in sync. It was also a pain to fix merge conflicts if a conference has too many topics. That's why I have decided to limit the max amount of topics to 3 and to not allow general conferences to also have other topics.

With Open Source I see the problem that a conference is Open Source related and Java related and JavaScript related and so on. Because we limit the topics per conference this could be a problem.

**Comment by cgrail** [comment]
> I created a draft PR with the necessary changes I have identified so far: #780

The PR looks good. But we would also need to add it here, because of the distributed nature of the project:
https://github.com/tech-conferences/conference-data/blob/main/scripts/config/topics.ts

**Comment by dellagustin-sap** [comment]
Related PR: https://github.com/tech-conferences/conference-data/pull/7261

> With Open Source I see the problem that a conference is Open Source related and Java related and JavaScript related and so on. Because we limit the topics per conference this could be a problem.

Just to record what we discussed by phone, there are a number of conferences centered around Open Source, e.g. FOSS Backstage, Open Source Summit, InnerSource Summit, etc..., so we decided that a dedicated topic would make sense.

One the changes from https://github.com/tech-conferences/conference-data/pull/7261 are live in production, then I think this issue can be considered complete.

**Comment by dellagustin-sap** [comment]
Thank you @cgrail !

**Comment by dellagustin-sap** [comment]
Thank you @nimzco .
A follow up question, what do you mean by _backend_ in this case? I first assumed it was https://github.com/tech-conferences/api.confs.tech, but I could not find a recent change there.
I'm trying to understand the architecture a bit more, in case I engage again with the project again.

**Comment by nimzco** [comment]
Right, the architecture is not straightforward. That's because when I built it, I based myself on the fact that the data is public and stored in GH.
So the API is a simple backend that parses the files on GH and creates a Conference object in the DB. It also attributes it a topic. 1 conference in the DB can have multiple topics. These topics are stored in the DB, that's how I know which files to look at when parsing GH.
And ultimately, this is synced with Algolia that will serve the frontend.

The end 😅

**Comment by dellagustin-sap** [comment]
Thank you @nimzco , 

> So the API is a simple backend that parses the files on GH and creates a Conference object in the DB. It also attributes it a topic. 1 conference in the DB can have multiple topics. These topics are stored in the DB, that's how I know which files to look at when parsing GH.
> And ultimately, this is synced with Algolia that will serve the frontend.

Where can I find the source code for that?

**Comment by nimzco** [comment]
That's the rails app in api.confs.tech :)

**Comment by dellagustin-sap** [comment]
> That's the rails app in api.confs.tech :)

@nimzco that was what I though, but I don't see any recent update on the main branch of https://github.com/tech-conferences/api.confs.tech, so, did I miss something? Did you mean something else with "We also have to create the topic in the backend for it to be effective on the website. I've just done that..."?
